1.18.4
/usr/bin
/usr/bin/cairo-trace
/usr/include/cairo
/usr/include/cairo/cairo-features.h
/usr/lib
/usr/lib/cairo
/usr/lib/cairo/libcairo-fdr.so
/usr/lib/cairo/libcairo-trace.so
/usr/lib/libcairo-gobject.so
/usr/lib/libcairo-gobject.so.2
/usr/lib/libcairo-gobject.so.2.11804.4
/usr/lib/libcairo-script-interpreter.so
/usr/lib/libcairo-script-interpreter.so.2
/usr/lib/libcairo-script-interpreter.so.2.11804.4
/usr/lib/libcairo.so
/usr/lib/libcairo.so.2
/usr/lib/libcairo.so.2.11804.4
/usr/lib/pkgconfig
/usr/lib/pkgconfig/cairo-fc.pc
/usr/lib/pkgconfig/cairo-ft.pc
/usr/lib/pkgconfig/cairo-gobject.pc
/usr/lib/pkgconfig/cairo-pdf.pc
/usr/lib/pkgconfig/cairo-png.pc
/usr/lib/pkgconfig/cairo-ps.pc
/usr/lib/pkgconfig/cairo-script-interpreter.pc
/usr/lib/pkgconfig/cairo-script.pc
/usr/lib/pkgconfig/cairo-svg.pc
/usr/lib/pkgconfig/cairo-tee.pc
/usr/lib/pkgconfig/cairo-xcb-shm.pc
/usr/lib/pkgconfig/cairo-xcb.pc
/usr/lib/pkgconfig/cairo-xlib-xrender.pc
/usr/lib/pkgconfig/cairo-xlib.pc
/usr/lib/pkgconfig/cairo.pc
